#feign:
#  oauth2:
#    enabled: true
#    clientRegistrationId: keycloak


spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login-app
            client-secret: wtcV1aFtw0VE0jgI6e9IN441xncFg2l4
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/SpringBootKeycloak/protocol/openid-connect/token

server:
  port: 8082